Assignment.create!([
  {course_id: 4, title: "Four Watercolors", description: "Use what you've learned to create four separate watercolors - a view, a plant, a photo, and a food. Curl up and sleep on the freshly laundered towels. I could pee on this if i had the energy attack the dog then pretend like nothing happened for chirp at birds. Sit by the fire dream about hunting birds toy mouse squeak roll over. Lick arm hair inspect anything brought into the house stand in front of the computer screen, ignore the squirrels, you'll never catch them anyway. Claw drapes hide from vacuum cleaner, kitty loves pigs and step on your keyboard while you're gaming and then turn in a circle but sit in window and stare ooo, a bird! yum meow for food, then when human fills food dish, take a few bites of food and continue meowing. Going to catch the red dot today going to catch the red dot today present belly, scratch hand when stroked. Then cats take over the world put toy mouse in food bowl run out of litter box at full speed but eat a plant, kill a hand so i like big cats and i can not lie jump off balcony, onto stranger's head lick plastic bags. Mark territory massacre a bird in the living room and then look like the cutest and most innocent animal on the planet but put toy mouse in food bowl run out of litter box at full speed but poop in the plant pot for nap all day, so lick butt, destroy couch as revenge. Flee in terror at cucumber discovered on floor.", deliverable: "Upload at least 1 of your four watercolors with a small description of what you learned while making the pieces. Feel free to upload all four!", materials: "watercolor paints, paper, water, brushes", resources: nil},
  {course_id: 1, title: "Address It!", description: "Use what you've learned to script your own letter and envelope, then upload a photo of the envelope. Envelopes can be a source of various challenges, variables, and opportunities — and they are typically at the core of a calligrapher's work. whether or not you select your own words or rewrite something you find instpirational,  you will have an attractive piece of writing at the end. This fun project is a excellent way to spend time with words you enjoy while improving your penmanship skills.", deliverable: "Use your new calligraphy skills address an envalope, and upload it here.", materials: "calligraphy nibs, pen holder, ink, and paper (your choice)", resources: nil},
  {course_id: 5, title: "Galaxy Watercolor", description: "Your assignment is to paint a fun, galaxy or nebula watercolor painting making use of techniques you learned during this course. Take a look at the attached photo examples or find your favourite space photo, or create something completely unique! The best paintings are a joy to make. Have fun this course, relax, and experiment in creating this project.", deliverable: "Upload your completed watercolor galaxy and a blurb about the process. Tell us about how you experimented!", materials: nil, resources: nil},
  {course_id: 3, title: "Blank for now", description: "Human give me attention meow chew on cable spit up on light gray carpet instead of adjacent linoleum lick sellotape so who's the baby. Cats secretly make all the worlds muffins stare out the window yet who's the baby meowing non stop for food. Claw drapes need to chase tail. Has closed eyes but still sees you go into a room to decide you didn't want to be in there anyway missing until dinner time, but attack feet eat and than sleep on your face, walk on car leaving trail of paw prints on hood and windshield. Steal the warm chair right after you get up kitty power! , pooping rainbow while flying in a toasted bread costume in space spot something, big eyes, big eyes, crouch, shake butt, prepare to pounce, so purrr purr littel cat, little cat purr purr. Licks your face why must they do that and sometimes switches in french and say 'miaou' just because well why not.", deliverable: "Will fill in later", materials: nil, resources: nil},
  {course_id: 6, title: "Blank for now", description: "Human give me attention meow chew on cable spit up on light gray carpet instead of adjacent linoleum lick sellotape so who's the baby. Cats secretly make all the worlds muffins stare out the window yet who's the baby meowing non stop for food. Claw drapes need to chase tail. Has closed eyes but still sees you go into a room to decide you didn't want to be in there anyway missing until dinner time, but attack feet eat and than sleep on your face, walk on car leaving trail of paw prints on hood and windshield. Steal the warm chair right after you get up kitty power! , pooping rainbow while flying in a toasted bread costume in space spot something, big eyes, big eyes, crouch, shake butt, prepare to pounce, so purrr purr littel cat, little cat purr purr. Licks your face why must they do that and sometimes switches in french and say 'miaou' just because well why not.", deliverable: "Will fill in later", materials: nil, resources: nil},
  {course_id: 7, title: "Blank for now", description: "Human give me attention meow chew on cable spit up on light gray carpet instead of adjacent linoleum lick sellotape so who's the baby. Cats secretly make all the worlds muffins stare out the window yet who's the baby meowing non stop for food. Claw drapes need to chase tail. Has closed eyes but still sees you go into a room to decide you didn't want to be in there anyway missing until dinner time, but attack feet eat and than sleep on your face, walk on car leaving trail of paw prints on hood and windshield. Steal the warm chair right after you get up kitty power! , pooping rainbow while flying in a toasted bread costume in space spot something, big eyes, big eyes, crouch, shake butt, prepare to pounce, so purrr purr littel cat, little cat purr purr. Licks your face why must they do that and sometimes switches in french and say 'miaou' just because well why not.", deliverable: "Will fill in later", materials: nil, resources: nil},
  {course_id: 8, title: "Blank for now", description: "Human give me attention meow chew on cable spit up on light gray carpet instead of adjacent linoleum lick sellotape so who's the baby. Cats secretly make all the worlds muffins stare out the window yet who's the baby meowing non stop for food. Claw drapes need to chase tail. Has closed eyes but still sees you go into a room to decide you didn't want to be in there anyway missing until dinner time, but attack feet eat and than sleep on your face, walk on car leaving trail of paw prints on hood and windshield. Steal the warm chair right after you get up kitty power! , pooping rainbow while flying in a toasted bread costume in space spot something, big eyes, big eyes, crouch, shake butt, prepare to pounce, so purrr purr littel cat, little cat purr purr. Licks your face why must they do that and sometimes switches in french and say 'miaou' just because well why not.", deliverable: "Will fill in later", materials: nil, resources: nil},
  {course_id: 2, title: "Quoatability", description: "You will produce a custom brush lettering piece of art with a quote or phrase. When complete, it will be perfect for hanging on your wall, offering as a present, placing on a card, or perhaps digitization. This project will enable you to practice overall lettering design, focusing on using your new skills to place your words in a visually pleasing place where they work together on paper.", deliverable: "Use your new calligraphy skills address an envalope, and upload it here.", materials: "calligraphy pens, watercolors, tombows, crayola markers - whatever you like!", resources: "Suggested pens: <a href='http://www.amazon.com/Tombow-Dual-Brush-Black-66621/dp/B001LDKB1S/ref=sr_1_9?s=office-products&ie=UTF8&qid=1445910929&sr=1-9&keywords=tombow'>Tombows</a> & <a href='http://www.amazon.com/Prismacolor-Premier-Illustration-Assorted-1738861/dp/B0038D7Y00/ref=sr_1_2?ie=UTF8&qid=1445910900&sr=8-2&keywords=prismacolor+brush+pen'>Prismacolors</a>"}
])
Attachment.create!([
  {attachable_type: "Assignment", attachable_id: 1, document_file_name: "Watercolor-For-Beginners.pdf", document_content_type: "application/pdf", document_file_size: 234278, document_updated_at: "2017-01-14 02:05:13"}
])
Course.create!([
  {title: "Modern Brush Calligraphy and Hand Lettering", description: "In this class we’ll be breaking down hand lettering and brush calligraphy and making it simple for you to learn! We'll cover the fundamentals, strokes, practice stokes, pen pressure, and the way to break all of those rules to form your own style. This course breaks down the basics of basic strokes necessary to properly use brush pens of all sizes. Starting using brush pens is a learning curve itself, apart from learning hand lettering. You want to get accustomed to the way to properly use the brush tip, as its variable pressure and thickness can make or break your piece. \nYou will learn simple strategies such as when to perform different motions with your fingers, wrists, and applying variable pressure, in conjunction with very desirable techniques like mixing color throughout your letters while drawing them and adding bounce to your hand lettering.", assignment_summary: "Make your favorite quote into a piece of lettering art", playlist_src: "https://www.youtube.com/embed/videoseries?list=PLTJAAMQ-RjD1MatWNEZo-8s1k5h-9j65f", cover_img_src: "https://s3.amazonaws.com/artistera-pro/cover-imgs/brush-lettering-md.jpg"},
  {title: "Introduction to Watercolors", description: "Learn to create beautiful watercolor illustrations with this series of basic watercolor tutorials by Scarlett Damen. This course is designed for the beginning watercolorist, but includes some full length intermediate lessons and speed painting demonstrations as well - so there is surely something to gain for even more experienced artists. You'll learn about proper materials including paints, brushes, and paper types, as well as how to mix colors, create washes, paint wet on wet, and more.\nFrom the creator:  'On WATERCOLOR by Scarlett Damen youll find lots of watercolor painting tutorials for beginners and new artists with simple step by step classes covering how to use watercolour and basics and beginner watercolor techniques. (everything from how to paint a graduated and veragrated wash, chasing the right watercolour paper, to using salt, plastic wrap, soap and alcohol in your paintings as lets not forget watercolour texture medium and of course everything you ever wanted to know about watercolour masking fluid to name a few.) Ive also created many full length watercolour lessons for intermediate and advanced watercolorists wanting to learn how to paint botanical art in watercolour. These classes include both speed paintings with commentary and full watercolor painting step by step demonstrations to help you learn to master watercolour techniques as well as a lots of art tips, watercolour facts and fun painting tricks to help you along your art journey.\nSee more of Scarlett's work at www.ScarlettDamenArtistIllustrator.com", assignment_summary: "Use what you've learned to create four separate watercolors - from a view, a plant, a food, and a photo. Share your favorite!", playlist_src: "https://www.youtube.com/embed/videoseries?list=PLnGy6GHuNNvT-B7r8ICqgDzQoY49aANgc", cover_img_src: "https://s3.amazonaws.com/artistera-pro/cover-imgs/watercolor-exercises-md.jpg"},
  {title: "Introduction to Charcoal Drawing", description: "This course introduces classical drawing principles in charcoal. In this class, you will learn materials to use as well as how to analyze light and shadow utilizing the 5-value system, apply form/cast shadow edge distinctions to model form using charcoal, and incorporate perspective, composition and value pattern concepts. You will also learn how to accurately draw portraits using gesture, correct proportions, and light and shade and practice anatomy and shapes for drawing the eyes, nose, mouth, hair, and ears. You will also practice using charcoal to depict landscapes and other objects. While you draw, you will also discover the subjects and techniques that work best for you in your charcoal projects.", assignment_summary: "Draw a portrait, landscape, or something from a reference photo.", playlist_src: "https://www.youtube.com/embed/videoseries?list=PLTJAAMQ-RjD3Z28e66B0SEaKwE6nL6PnA", cover_img_src: "https://s3.amazonaws.com/artistera-pro/cover-imgs/intro-charcoal-md.jpg"},
  {title: "Watercolor Exercises", description: "Tune in with Meredith from The Witty Gritty Paper Co. for some super valuable tips on how to avoid beginner mistakes and master this awesome medium in no time. This approachable collection of beginner exercises and tutorials will give you confidence and help you find your own style in no time.\n<em>What to expect from this class:</em>\nPainting inspiration!\nA variety of demos and tutorials\nBasic principles of color theory and how to use watercolors\nRecommended materials specific to every tutorial", assignment_summary: "When I get around to writing this, the project is upload your favorites from following along", playlist_src: "https://www.youtube.com/embed/videoseries?list=PLTJAAMQ-RjD0Dux53ndLcOB1Hm1lyW03k", cover_img_src: "https://s3.amazonaws.com/artistera-pro/cover-imgs/watercolor-intro-md.jpg"},
  {title: "Pointed Pen Calligraphy 101", description: "A 9 video introduction to pointed pen calligraphy for beginners, from OpenInkStand Art & Calligraphy. This warm and inviting beginner course covers the basic techniques, tools, and tips for creating gorgeous calligraphy. Whether youre a seasoned calligraphist or a total beginner this course provides you the tools to transform your work. Each lesson is full of insider tips, from how different styles of nibs affect your slant to how your breathing can influence your writing.\n<em>You'll find out how to:\n</em>Improve your slants, strokes, and spacing technique\nElevate your capital letters and flourishes\nCultivate your personal penmanship style", assignment_summary: "Use your new skills to write a letter and address an envelope in calligraphy", playlist_src: "https://www.youtube.com/embed/videoseries?list=PLTJAAMQ-RjD3LTvgDjirM835uCCwvuASw", cover_img_src: "https://s3.amazonaws.com/artistera-pro/cover-imgs/pointed-pen-callig-md.jpg"},
  {title: "Knitting 101", description: "Learn to knit with Knitting 101 by NEW STITCH A DAY. In this class, you'll first learn how to to make a slip knot. The slip knot is the very first thing you must make before starting most knitting projects, as you need to know how to make a slip not in order to begin most cast ons. Next the class will break down the basics, including the four fundamental techniques at the heart of knitting the cast on, the knit stitch, the purl stitch, and the cast off. By the end, youll have your very own scarf, and the skills to begin more new and exciting knitting projects.\nCheck out written instructions at <a href='http://newstitchaday.com/category/guides/knitting-101/'>http://newstitchaday.com/category/guides/knitting-101/</a>", assignment_summary: "Make a basic scarf", playlist_src: "https://www.youtube.com/embed/videoseries?list=PLR1ElIXW5YKJFob5KJvHS01Tj30Zyy2EQ", cover_img_src: "https://s3.amazonaws.com/artistera-pro/cover-imgs/knitting-101-md.jpg"},
  {title: "Drawing Lessons for Beginners", description: "In this series of videos from the Art of Wei, you will learn the basics and how to get started drawing your own beautiful life-like pencil portraits.  This is an in-depth investigation into basic drawing principles which face both fine artists and illustrators. Composition, perspective, proportion, focal point, value pattern and the use of light and shadow are developed. We'll cover: \n<em>Materials:</em> Which materials and references will make for the best portraits.\n<em>Basic Sketching:</em> How to compose your basic sketch through gesture and accurate proportions.Planes. How to understand light and shade on the planes of the face.\n<em>Features and Forms:</em> How to structure the forms of your subject's eyes, nose, mouth, and hair. \n<em>Finishing Touches:</em> How to capture those finishing details that will really make your portrait special.\nThis drawing course deals with the understanding and application of perspective, proportion, gesture, and foreshortening. Through the use of line, tone, and modeling, students will learn to depict objects as wells as figures.", assignment_summary: "Attempt a portrait in pencil from a reference photo.", playlist_src: "https://www.youtube.com/embed/videoseries?list=PLhnHFsOn0cgdjNrlX4qeytqAUIhRqKbAI", cover_img_src: "https://s3.amazonaws.com/artistera-pro/cover-imgs/begging-drawing-md.jpg"},
  {title: "Mixed Media Art Journaling", description: "In this course from Maremi SmallArt, students will discover new possibilities by mixing media and using varied drawing surfaces to create art journaling layouts and mixed media art. This is a perfect series for every art journaler and mixed media artist, for those who are just beginning and also for those who already have a passion for creating! This course will teach you techniques to start an art journaling practice, covering everything from how to break in a page to how to use various mediums and surfaces to add texture and vitality, as well as convey a personal expression. Demos will focus on design, balance, weight, texture,  and the appropriate use of mediums.\n<em>This class contains:</em>\nAn introduction to mixed media for beginners\nAn overview of supplies and how to use them\nDemonstrations\nAnd an art challenge!", assignment_summary: "Your assignment is to do a 10 minute art challege, like Marta does in the last video", playlist_src: "https://www.youtube.com/embed/videoseries?list=PLTJAAMQ-RjD1w-qGjjqDUG3sP4RFYBca2", cover_img_src: "https://s3.amazonaws.com/artistera-pro/cover-imgs/mixed-media-md.jpg"}
])
Project.create!([
  {title: "A Sample Submission", description: "Howl on top of tall thing attack feet sit on human for use lap as chair jump off balcony, onto stranger's head, or licks your face for friends are not food. Gate keepers of hell meowing non stop for food why must they do that. Lies down meow all night having their mate disturbing sleeping humans and thug cat meowzer! so chew foot, or sit in window and stare ooo, a bird! yum yet lick yarn hanging out of own butt. Brown cats with pink ears destroy couch, or who's the baby. Sit on the laptop hide from vacuum cleaner.", user_id: 1, assignment_id: 1, cover_img_file_name: "watercolor-in-progress.jpeg", cover_img_content_type: "image/jpeg", cover_img_file_size: 16283, cover_img_updated_at: "2017-01-13 22:52:39"}
])
Review.create!([
  {body: "Great class that inspired me to create and keep practicing! Thank you sooo much!", user_id: 8, course_id: 1},
  {body: "Excellent introduction! Thorough without being dull.", user_id: 15, course_id: 1},
  {body: "It's well explained and does a good job teaching all the basics.", user_id: 6, course_id: 1},
  {body: "It's my first time trying pointed pen calligraphy and this class really helped me.", user_id: 9, course_id: 1},
  {body: "A nice intro into Caligraphy. This makes the art seem very achievable for all! I look forward to designing calligraphy with my favorite quotes", user_id: 13, course_id: 2},
  {body: "Highly Recommended! I have wanted to take a calligraphy class forever and am very glad this is where I started.", user_id: 1, course_id: 2},
  {body: "This class explains everything you need to know to get started with attractive hand lettering. Very detailed and clear explanations.", user_id: 4, course_id: 2},
  {body: "This course does a great job introducing you to the beginning steps of learning modern calligraphy!", user_id: 10, course_id: 2},
  {body: "Great techniques and great instructors. Everything is explained very well with demostrations.", user_id: 9, course_id: 2},
  {body: "I learned so much! This was a really great class. Highly recommended.", user_id: 3, course_id: 4},
  {body: "Excellent beginners tutorial. Scarlett is a great teacher -  I love her style. So many great tips and ideas on how to become a better watercolorist!", user_id: 9, course_id: 4},
  {body: "Great instruction! Very detailed and clear explanations, with answers to all my questions before they even popped into my head!", user_id: 7, course_id: 4},
  {body: "I wholeheartedly recommend this class.  As long as you're not too ambitious in your project, you will have something really cool at the end.", user_id: 2, course_id: 4},
  {body: "The videos for this class are extremely helpful.  I watched it once through before even picking up my tools, just to understand the process and visualize.", user_id: 12, course_id: 4},
  {body: "This is a very beginner friendly course! I've really enjoyed the lessons so far :)", user_id: 1, course_id: 5},
  {body: "This is a great beginners watercolors class! Loved how simple it was, how clear. I think I'll be returning to the class and the exercises many times as I start my watercolor practice.", user_id: 10, course_id: 5},
  {body: "As an aspiring artist, I wholeheartedly recommend this class. The course materials are awesome and the lessons are great fun.", user_id: 5, course_id: 5},
  {body: "Excellent beginners tutorial. I really learned so much from this class. By the end of the course you really feel comfortable with your own work.", user_id: 13, course_id: 5},
  {body: "This class is useful and inspiring and provides a lot of helpful tips for someone who is a beginner like me! Thank you.", user_id: 8, course_id: 3},
  {body: "Awesome class and instructor, picked up lots of great tips. Wonderful talent!", user_id: 5, course_id: 3},
  {body: "I love to create and design, and art journaling is such a fun way to boost your creativity! This was a very cool class with lots of usefull information", user_id: 2, course_id: 3},
  {body: "Another high quality set of tutorials. Highly recommended! I'm looking forward to applying these techniques in my own art journals.", user_id: 14, course_id: 3},
  {body: "Really good class. Good place to start if you are a lost begginer. Excellent teacher, very organized, well prepared.", user_id: 4, course_id: 7},
  {body: "Very very informative! Thorough without being dull. Wish I had taken this course months ago!", user_id: 5, course_id: 7},
  {body: "Perfectly accessible for a complete newbie. Thank you so much, I will definitely try the project! :)", user_id: 12, course_id: 7},
  {body: "Easy to follow instructions in pretty short and clear very useful videos. Fantastic class !", user_id: 14, course_id: 7},
  {body: " Very good explanations of how things work, easy to follow, and great examples. I will be going through all these lessons again very soon.", user_id: 1, course_id: 7},
  {body: "This class is very technical, academic and detailed. Good for beginners and for those wishing to refresh on their basic skills. ", user_id: 3, course_id: 8},
  {body: "This class really breaks down the tips I needed to work on key elements in such a quick and easy way.  Would recommend it it to anyone wants to learn drawing professionally.", user_id: 11, course_id: 8},
  {body: "Simple and effective lecturing. I learned new techniques that I haven't tried before and it was fun to see how my work improved. ", user_id: 6, course_id: 8},
  {body: "An excellent class on realistic pencil drawing .  Everything flowed and made sense, and was really well explained. ", user_id: 12, course_id: 8},
  {body: "Great Class! Loved it! After this class my drawing improved quite dramatically.", user_id: 13, course_id: 6},
  {body: "Fantastic techniques, clear guidelines. Observing these artists' work has made my own charcoal portraits so much better.", user_id: 4, course_id: 6},
  {body: "Great advice for those who are new to drawing and very inspiring for experience artists. Just brilliant!", user_id: 15, course_id: 6},
  {body: "Well researched class with good coverage of the basics of light/shade and foundational techniques. I had so many aha moments throughout this course.", user_id: 9, course_id: 6},
  {body: "This is the best online drawing course I have taken! Definitely worth watching if you're wanting to improve your charcoal skills.", user_id: 8, course_id: 6}
])
User.create!([
  {email: "castelino.darocha@example.com", gravatar_hash: "b433949a308c0643a2b9e854bb40ae84", first_name: "Castelino", last_name: "Da Rocha", password_digest: "$2a$10$9XM8orC4ltZX2vyGq2nmp.yL8dPVLOrYZUcnc2EUcmOy/vhh.zpTu", session_token: "AYbslXN15PUf-ZbaSSHkHg"},
  {email: "ana.cano@example.com", gravatar_hash: "5df11d4473cc48067bee0e900b977809", first_name: "Ana", last_name: "Cano", password_digest: "$2a$10$.TgfU4cyGFbIsrorNICoeO70EEuIHAIkFZpD/BpB7..mbFKUn/Khu", session_token: "db9D4JhCfAQYcIovQWI9TA"},
  {email: "albert.thomsen@example.com", gravatar_hash: "8b52b0859aee5d1f6fa3b70c1875f0ac", first_name: "Albert", last_name: "Thomsen", password_digest: "$2a$10$V.jyT6H9cv/rfOIeChQyVeCsAwrZc0pLhYVrbTTPgDf3SysRJUkmW", session_token: "roExws2-kr7gopLK6TFydA"},
  {email: "paulina.menheere@example.com", gravatar_hash: "a43677963e94375f48b0e7fcb63f109c", first_name: "Paulina", last_name: "Menheere", password_digest: "$2a$10$3Nd6QyhfiR6t13.3hA7nbOT0E.C7xZ2UHQdXTfV6i.JDhvTuoI4wG", session_token: "M6pUKIgFi62EDjz0clju2Q"},
  {email: "stefanie.klein@example.com", gravatar_hash: "1bd22bc3f138986dcdcd5ceed518c1c6", first_name: "Stefanie", last_name: "Klein", password_digest: "$2a$10$5/RwnrV43rd..K.QU8kYHuYriUQVN7TAymx6O3c2Vab9FRSAIVnFu", session_token: "YiRMswoflGZAoIZmjWQn6A"},
  {email: "artisterademo@gmail.com", gravatar_hash: "ff5b0e7faa0695130043f8993542b864", first_name: "Chloe", last_name: "Evans", password_digest: "$2a$10$L3434XPB0HylpJEqmsplmOJ5mhAt4QF4OO2kDbWEsnF1BMGmHlkB6", session_token: "owO2MEXYQG2D3XyF8drsZA"},
  {email: "artistera.demo@gmail.com", gravatar_hash: "a679b1c08b90e81fe1ff21bb27b6dbe2", first_name: "Helena", last_name: "Berndt", password_digest: "$2a$10$m8DbiQyctqeaeBlo/27n4etj/3wBsoq6q4hA7O1kKY2.6vKXf3Gae", session_token: "MHm_cauIv8LlCTglWSj2mA"},
  {email: "artiste.ra.demo@gmail.com", gravatar_hash: "bbc2072bbdb76ea1bedf2cb45305795c", first_name: "Amalie", last_name: "Nielsen", password_digest: "$2a$10$xJFN6.rivkX7Gfp0Xexve.5TiodkqPjBvvduRwZ3TiF2O5aRc9oxi", session_token: "HWNEErUAtWQPBOpSNvKlLA"},
  {email: "a.rtisterademo@gmail.com", gravatar_hash: "c1034001f2d477728266da955ad6623b", first_name: "David", last_name: "Barnaby", password_digest: "$2a$10$5a6M8xHQXCfhELnI.fLaE.vHpB1lkKC4nz0XrCBuRopOjKjLBu79q", session_token: "A2praXlIufJcH6tG3RjH9A"},
  {email: "art.isterademo@gmail.com", gravatar_hash: "ac686d96f8aecdcca7be329cbba405b3", first_name: "Aubree", last_name: "Park", password_digest: "$2a$10$G.gmKVZNS6GHx2vfeiEJt.q9RJBY8siKSfRsS39Q7pJ5HWDrQcg.C", session_token: "UnkPjzJe9RlO2rk1XxMi6A"},
  {email: "artist.era.demo@gmail.com", gravatar_hash: "53640e92d47d2658b99097a5b69d5dde", first_name: "Claire", last_name: "Laurent", password_digest: "$2a$10$zymgFSqHUFmB/23fRePQdO2dbEU.VBTKP.5rkSkRyY/0u.dzWh3HK", session_token: "swE2xoOnBVfP1RCFbB2Ytg"},
  {email: "artisterademo+bronwyn@gmail.com", gravatar_hash: "f8f9aad6aa309a76d5dce56f8e5764fb", first_name: "Bronwyn", last_name: "Dunn", password_digest: "$2a$10$Qn0c/TcRX2JvpmIkmAYYO.pB2dKSbqjt7cq.ejWML.VJT2N/CrmYi", session_token: "FMOHt_iiBxSDU44xXDh_Ag"},
  {email: "artisterademo+lauren@gmail.com", gravatar_hash: "d9053d00075c5027a16a07c15c1bae0b", first_name: "Lauren", last_name: "Madigan", password_digest: "$2a$10$YCg.onNoW8OBxCSxhWLpXuEiVmCb9.wM8sCXDIX.snlqaELDD/3Tu", session_token: "DTSZvyUzx-_x_IQrqo8qiQ"},
  {email: "demo@artistera.info", gravatar_hash: "ecd49fd7190ec2cbe55015b7f7c0eb9a", first_name: "Demonstration", last_name: "User", password_digest: "$2a$10$LZ8w0dR6ixQmYmlgL2FG0e8d4grBRyv2I0z6MwUhM7fLy8Em5GiKS", session_token: "Ku8e7U8dvDrBXHmrW0RUwQ"},
  {email: "katarina.n.rossi@gmail.com", gravatar_hash: "3ae05d6d1b8b0a23c4c6aeb061a13290", first_name: "Katarina", last_name: "Rossi", password_digest: "$2a$10$9GC3AiO0xaF5OTzuEHC5TO1QiFHIB8FIaHqgt9ycEGRXfKKuNYovC", session_token: "Hr0OHiyIIhG36AsrNVfHhg"}
])
